# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a vector with values ranging from 10 to 49

In [4]:
vec=np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
vec.shape

(40,)

5. Print the type of the previous array in question 3

In [6]:
vec.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Documents/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Documents/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Documents/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\w

7. Print the dimension of the array in question 3


In [8]:
vec.ndim

1

8. Create a boolean array with all the True values

In [9]:
arr1=np.array([1,2,3,4])
arr2=np.array([12,13,14,15])
arr1<arr2

array([ True,  True,  True,  True])

9. Create a two dimensional array




In [10]:
lst=[[1,2,3,4,5],[6,7,8,9,10]]
d2array=np.array(lst)
print(d2array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


10. Create a three dimensional array



In [11]:
lst1=[
    [[1,2,3,4],[5,6,7,8]],
      [[1,2,3,4],[5,6,7,8]]
]
d3array=np.array(lst1)
d3array

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
vec1=np.array([1,2,3,4,5,6,7,8,9,10])
vec1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype('float64')

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [21]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1==arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [22]:
odd=np.arange(10)
odd[1::2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [23]:
odd[1::2]=-1
odd

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [24]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [25]:
y=np.zeros((2,4))
y[0:2,0]=1
y[0:2,3]=1
y

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [26]:
arr2d = np.array([[1, 2, 3],

            [4,5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,0:3]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [28]:
arr2=[[0,1,2,3,4],[5,6,7,8,9]]
arr2=np.array(arr2)
arr2[0,::]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [29]:
arr2=[[0,1,2,3,4],[5,6,7,8,9]]
arr2=np.array(arr2)
arr2[1,1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [31]:
arr2=[[0,1,2,3,4],[5,6,7,8,9]]
arr2=np.array(arr2)
arr2[2:,3:]
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
rand=np.random.randn(10,10)
rand
print(rand.min())
print(rand.max())

-2.5228556653855683
2.176724653473935


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.unique((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print('\n',data[names!="Will"])

[[ 0.61015649 -1.30957673  1.43353458  0.12904903]
 [ 0.47673585  0.67260509 -0.7551609   0.54693201]
 [-0.32505968  2.17295512  0.86412538  0.9086467 ]
 [-0.47694316 -1.46202333 -0.18064208 -0.52955462]
 [ 0.21814921  0.35771414 -0.03309942 -2.010054  ]
 [ 0.4910314   1.03570396  0.34698895  0.69082283]
 [ 0.19248471  1.53484701  0.54839164 -0.33582166]]

 [[ 0.61015649 -1.30957673  1.43353458  0.12904903]
 [ 0.47673585  0.67260509 -0.7551609   0.54693201]
 [-0.47694316 -1.46202333 -0.18064208 -0.52955462]
 [ 0.4910314   1.03570396  0.34698895  0.69082283]
 [ 0.19248471  1.53484701  0.54839164 -0.33582166]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names=="Bob"]

array([[ 0.90108443,  0.29504818,  0.06941715,  0.07573079],
       [-2.15102632, -1.20258723, -1.32135496, -0.00492896]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:
t_d1=np.arange(1,16).reshape(5,3)
t_d1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [38]:
t_d=np.arange(1,17,1).reshape(2,2,4)
t_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [39]:
t_d[0][1]=t_d[1][0]
t_d

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [40]:
size_of_array=np.arange(10)
size=np.sqrt(size_of_array)                  
print(size)
result=np.where(size<0.5, 0,size_of_array)
print(result)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0 1 2 3 4 5 6 7 8 9]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [41]:
a1=np.array([2,3,6,7,4,8,9,5,3,6,7,8])
a2=np.array([4,5,6,7,3,7,9,9,6,4,1,6])
np.maximum(a1,a2)

array([4, 5, 6, 7, 4, 8, 9, 9, 6, 6, 7, 8])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [42]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
names.sort()
names

['Bob' 'Joe' 'Will']


array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [48]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
if np.where(a==b);

SyntaxError: invalid syntax (<ipython-input-48-f72c959228b9>, line 3)

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [46]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[0,1]=newColumn[0,0]
sampleArray[1,1]=newColumn[0,1]
sampleArray[2,1]=newColumn[0,2]
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [44]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [45]:
r_v=np.random.randn(4,5)
np.cumsum(r_v)

array([ 1.1309027 ,  0.99967139,  0.44678586,  0.84860041,  0.8317851 ,
        0.92849667,  0.83350178,  0.05133344,  1.72685366, -0.18120761,
        0.89697019,  0.85940591,  0.88970783,  1.22709349,  1.48256123,
        2.06141471,  3.45197026,  2.08350866,  3.7103004 ,  2.69656075])