# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
import numpy as np
x=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [19]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9],[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack(a)


array([[3.82873848],
       [5.61489609]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
x=np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.vstack(x)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [20]:
x=np.array([[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19]])
print('\n',x,'\n')
print(x.ravel())
print(x.flatten())


 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [21]:
x=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
x.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [22]:
x=np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11],[12, 13, 14]])
np.vstack(x)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [24]:
x=np.random.normal((5,5))
print(x,'\n')
print(np.sqrt(x))

[5.89929645 4.48724776] 

[2.42884673 2.11831248]


## Question:8

### Create 5x6 an array and find the mean?

In [25]:
x=np.random.gamma((5,6))
print(x)
print('\n',x.mean())

[5.59745797 1.56231559]

 3.5798867773497713


## Question:9

### Find the standard deviation of the previous array in Q8?

In [26]:
np.std(x)

2.0175711886284464

## Question:10

### Find the median of the previous array in Q8?

In [27]:

np.median(x)

3.5798867773497713

## Question:11

### Find the transpose of the previous array in Q8?

In [28]:
np.transpose(x)


array([5.59745797, 1.56231559])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [29]:
x=np.arange(16).reshape(4,4)
print(x)
print('Sum =',np.trace(x))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum = 30


## Question:13

### Find the determinant of the previous array in Q12?

In [31]:
print(np.linalg.det(x))
print(np.linalg.det([[1,2],[3,4]]))

0.0
-2.0000000000000004


## Question:14

### Find the 5th and 95th percentile of an array?

In [32]:

print(x)
print('\n',np.percentile(x,5))
print(np.percentile(x,95))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [33]:
print(x)
print('\n',np.isnan(x))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
